// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sobqxmuptbqswlworpei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnF4bXVwdGJxc3dsd29ycGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTIzODgsImV4cCI6MjA2NTU4ODM4OH0.0YrZxhffOjMC4WblxFlYUN07zUyEl6hf726mQCFTgTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);